export const GET_REPOS = "GET_REPOS";

export const GET_REPOS_BY_NAME = "GET_REPOS_BY_NAME";

export const GET_TOTAL_COUNT_REPOS = "GET_TOTAL_COUNT_REPOS";
export const RESET_TOTAL_COUNT_REPOS = "RESET_TOTAL_COUNT_REPOS";

export const ADD_REPO_TO_BOOKMARKS = "ADD_REPO_TO_BOOKMARKS";
export const REMOVE_REPO_FROM_BOOKMARKS = "REMOVE_REPO_FROM_BOOKMARKS";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
