export const GET_REPOS = "GET_REPOS";
export const GET_REPOS_BY_NAME = "GET_REPOS_BY_NAME";
export const GET_TOTAL_COUNT_REPOS = "GET_TOTAL_COUNT_REPOS";
export const RESET_TOTAL_COUNT_REPOS = "RESET_TOTAL_COUNT_REPOS";
export const ADD_REPO_TO_BOOKMARKS = "ADD_REPO_TO_BOOKMARKS";
